name: telegram deneme
on:
  schedule:
  - cron: "15 9,19 * * *"
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Beni ihmal ediyorsun sayin beni gelistiren vatandas. 
            Bu mesaji atan servis = 
            https://github.com/ismailbozkurt/actions_test/blob/main/.github/workflows/main.yml dosyasidir.
            Samsunlulari ayiklama dernegi.
            
